<a href="https://colab.research.google.com/github/msnaspers/ml-pg2025/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.19.0


In [5]:
scalar = tf.constant(7)

In [6]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
scalar.ndim

0

In [8]:
vector=tf.constant([1,2])

In [9]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [10]:
vector.ndim

1

In [11]:
matrix = tf.constant([[2,3],[4,6]])

In [12]:
matrix.ndim

2

In [13]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 6]], dtype=int32)>

In [14]:
matrix[1][0]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [15]:
another_matrix= tf.constant([[2,3],[3,7]], dtype=tf.float64)

In [16]:
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2., 3.],
       [3., 7.]])>

In [19]:
tensor = tf.constant([[[1,2,7],[2,9,7]],[[3,8,9],[6,9,6]]])

In [20]:
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 7],
        [2, 9, 7]],

       [[3, 8, 9],
        [6, 9, 6]]], dtype=int32)>

In [21]:
tensor.ndim

3

In [22]:
zmienny_tensor= tf.Variable([1,2])

In [23]:
zmienny_tensor[1].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 5], dtype=int32)>

In [24]:
zmienny_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 5], dtype=int32)>

In [30]:
random1=tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(10,10))

In [31]:
random1

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763,
        -1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
       [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ,
         1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
       [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 , -0.48293006,
        -0.52447474, -1.0345329 ,  1.3066901 , -1.5184573 , -0.4585211 ],
       [ 0.5714663 , -1.5331722 ,  0.45331386,  1.1487608 , -1.2659091 ,
        -0.47450137,  2.006022  ,  0.28288034, -0.30288252, -1.443651  ],
       [ 1.0034493 ,  0.20857747,  0.35700995,  1.0648885 ,  1.2432485 ,
        -2.2173238 ,  0.18706243,  0.6617961 ,  0.01380118, -0.24827152],
       [ 1.2111493 , -0.7199124 , -0.04082382,  2.6791053 ,  1.0914806 ,
         0.33149615, -0.67958915,  0.44723678, -0.17811584,  0.24882518],
       [ 0.49689844,  0.8259971 ,  1.0340209 , -0.24918638, -1.57802

In [32]:
tf.random.shuffle(random1)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[ 0.49689844,  0.8259971 ,  1.0340209 , -0.24918638, -1.5780283 ,
        -0.92161775,  0.268676  ,  0.9418312 , -0.9465717 , -0.7108357 ],
       [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763,
        -1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
       [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ,
         1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
       [ 0.5714663 , -1.5331722 ,  0.45331386,  1.1487608 , -1.2659091 ,
        -0.47450137,  2.006022  ,  0.28288034, -0.30288252, -1.443651  ],
       [-2.5255601 ,  0.05080947,  1.7212061 , -0.6575125 ,  0.7939443 ,
         1.3212339 ,  0.34584793, -0.6699328 ,  0.4604257 ,  0.514933  ],
       [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 , -0.48293006,
        -0.52447474, -1.0345329 ,  1.3066901 , -1.5184573 , -0.4585211 ],
       [ 1.2995545 , -0.6149066 , -1.4713507 , -0.10086866,  0.96038

In [33]:
tf.ones(shape=(10,10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [34]:
tf.zeros(shape=(10,10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [37]:
import numpy as np

In [44]:
numpy_A = np.arange(1,25, dtype=float)
A = tf.constant(numpy_A, shape=[2,12])
A

<tf.Tensor: shape=(2, 12), dtype=float64, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.]])>

In [46]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))

In [47]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>